bc_test:
    evaluation_agent: true
    featurize_type: bc
    held_out: true
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/bc_test.pt
    policy_config_path: config/asymmetric_advantages/bc_policy_config.pkl
    train: false
bc_train:
    evaluation_agent: true
    featurize_type: bc
    held_out: true
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/bc_train.pt
    policy_config_path: config/asymmetric_advantages/bc_policy_config.pkl
    train: false
comedi_mp0:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp0_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp1:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp1_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp2:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp2_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp3:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp3_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp4:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp4_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp5:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp5_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp6:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp6_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
comedi_mp7:
    featurize_type: ppo
    held_out: false
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/comedi_mp7_actor.pt
    policy_config_path: config/asymmetric_advantages/comedi_mp_policy_config.pkl
    train: false
coordinator:
    featurize_type: ppo
    policy_config_path: config/asymmetric_advantages/rnn_policy_config.pkl
    train: true
sp10_final:
    evaluation_agent: true
    featurize_type: ppo
    held_out: true
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/sp10_final_actor.pt
    policy_config_path: config/asymmetric_advantages/mlp_policy_config.pkl
    train: false
sp10_mid:
    evaluation_agent: true
    featurize_type: ppo
    held_out: true
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/sp10_mid_actor.pt
    policy_config_path: config/asymmetric_advantages/mlp_policy_config.pkl
    train: false
sp9_final:
    evaluation_agent: true
    featurize_type: ppo
    held_out: true
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/sp9_final_actor.pt
    policy_config_path: config/asymmetric_advantages/mlp_policy_config.pkl
    train: false
sp9_mid:
    evaluation_agent: true
    featurize_type: ppo
    held_out: true
    model_path:
        actor: pop_data/asymmetric_advantages_comedi/models/sp9_mid_actor.pt
    policy_config_path: config/asymmetric_advantages/mlp_policy_config.pkl
    train: false
